ccflags-y := -Idrivers/media/rc

obj-$(CONFIG_HISI_NEC_SIMPLE_ATTO)		+= ir-keymap-nec-atto.o
obj-$(CONFIG_HISI_NEC_SIMPLE_HISILICON)	+= ir-keymap-nec-hisilicon.o
obj-$(CONFIG_HISI_IR)					+= ir-hisi.o