/******************************************************************************

  Copyright (C), 2012-2050, Hisilicon Tech. Co., Ltd.

 ******************************************************************************
  File Name     : hal_hdmirx.h
  Version       : Initial Draft
  Author        : Hisilicon multimedia software group
  Created       : 2014/01/16
  Description   : 
  History       :
  1.Date        : 2014/01/16
    Author      : t00202585
    Modification: Created file
******************************************************************************/
#ifndef __HAL_HDMIRX_H__
#define __HAL_HDMIRX_H__

#include "hi_type.h"
#include "hi_unf_hdmirx.h"
#include "drv_hdmirx.h"

#define HDMIRX_REGS_ADDR	0xF8500000
#define HDMIRX_REGS0_ADDR	0xFF2C0000
#define HDMIRX_REGS_SIZE    0x10000
                
#define P1_CEC_ADDR 0x20
#define P2_CEC_ADDR 0x30
#define P3_CEC_ADDR 0x40

#ifndef HI_FPGA
#define HDMIRX_XCLK 5529600 // 2048*27MHz UNIT OF 10kHz
#endif

#ifdef HI_FPGA
#define HDMIRX_XCLK 4915200 // 2048*24MHz UNIT OF 10kHz
#endif

#define	INTR3_SERVING_PACKETS_MASK (intr_new_mpeg | intr_new_aud | intr_new_spd | intr_new_avi)


enum 
{
    HDMIRX_INTR1 = 0,
    HDMIRX_INTR2,
    HDMIRX_INTR3,
    HDMIRX_INTR4,
    HDMIRX_INTR5,
    HDMIRX_INTR6,
    HDMIRX_INTR7,
    HDMIRX_INTR8 = 7,
    HDMIRX_INTR2_AON,
    HDMIRX_INTR6_AON,
    HDMIRX_INTR8_AON,
    HDMIRX_INTR_BUTT
};
typedef enum hiHDMIRX_INFOFRAME_E
{
	HDMIRX_AVI   = 0x82, //!< AVI InfoFrame
	HDMIRX_SPD   = 0x83, //!< SPD InfoFrame
	HDMIRX_AUDIO = 0x84, //!< Audio InfoFrame
	HDMIRX_MPEG  = 0x85, //!< MPEG InfoFrame
	HDMIRX_ISRC1 = 0x05, //!< ISRC1 InfoPacket
	HDMIRX_ISRC2 = 0x06, //!< ISRC2 InfoPacket
	HDMIRX_ACP   = 0x04, //!< ACP InfoPacket
	HDMIRX_GC    = 0x03, //!< General Control InfoPacket
	HDMIRX_GBD   = 0x0A, //!< GBD InfoPacket
	HDMIRX_VSIF  = 0x81, //!< VSIF InfoFrame
}HDMIRX_INFOFRAME_E;

typedef enum hiHDMIRX_COLOR_SPACE_E
{
	HDMIRX_COLOR_SPACE_RGB,
	HDMIRX_COLOR_SPACE_YCBCR422,
	HDMIRX_COLOR_SPACE_YCBCR444,
	HDMIRX_COLOR_SPACE_BUTT
} HDMIRX_COLOR_SPACE_E;

typedef enum hiHDMIRX_OVERSAMPLE_E
{
    HDMIRX_OVERSAMPLE_NONE,
    HDMIRX_OVERSAMPLE_2X,
    HDMIRX_OVERSAMPLE_3X,
    HDMIRX_OVERSAMPLE_4X,
    HDMIRX_OVERSAMPLE_5X,
    HDMIRX_OVERSAMPLE_6X,
    HDMIRX_OVERSAMPLE_7X,
    HDMIRX_OVERSAMPLE_8X,
    HDMIRX_OVERSAMPLE_9X,
    HDMIRX_OVERSAMPLE_10X,
    HDMIRX_OVERSAMPLE_BUTT,
}HDMIRX_OVERSAMPLE_E;


typedef enum hiHDMIRX_RGB_RANGE_E
{
	HDMIRX_RGB_DEFAULT,
	HDMIRX_RGB_LIMIT_RANGE,
	HDMIRX_RGB_FULL_RANGE,
	HDMIRX_RGB_RANGE_BUTT
} HDMIRX_RGB_RANGE_E;

/**
* @brief RX video color depth
*/
typedef enum hiHDMIRX_INPUT_WIDTH_E
{
	HDMIRX_INPUT_WIDTH_24, //!< Color Depth is 8 bit per channel, 24 bit per pixel
	HDMIRX_INPUT_WIDTH_30, //!< Color Depth is 10 bit per channel, 30 bit per pixel 
	HDMIRX_INPUT_WIDTH_36, //!< Color Depth is 12 bit per channel, 36 bit per pixel
	HDMIRX_INPUT_WIDTH_48, //!< Color Depth is 16 bit per channel, 48 bit per pixel
	HDMIRX_INPUT_WIDTH_BUTT
}HDMIRX_INPUT_WIDTH_E;

typedef enum hiHDMIRX_INTERRUPT_IDX
{
	HDMIRX_INT_CTS,
	HDMIRX_INT_NEW_AUD_PACKET,
	HDMIRX_INT_NEW_AUD,
	HDMIRX_INT_VRES_CHG,
	HDMIRX_INT_AUD_MUTE,
	HDMIRX_INT_HW_CTS_CHG,
	HDMIRX_INT_CTS_DROP_ERR,
	HDMIRX_INT_CTS_REUSE_ERR,
	HDMIRX_INT_NEW_SPD,
	HDMIRX_INT_NEW_MPEG,
	HDMIRX_INT_ACP,
	HDMIRX_INT_CP,
	HDMIRX_INT_AVI,
	HDMIRX_INT_AUDIO_FIFO,
	HDMIRX_INT_SCDT,
	HDMIRX_INT_CP_MUTE,
	HDMIRX_INT_NO_AVI,
	HDMIRX_INT_AUDIO_MUTE,
	HDMIRX_INT_FIFO_OF,
	HDMIRX_INT_FIFO_UF,
	HDMIRX_INT_MAX_
}HDMIRX_INTERRUPT_IDX;

/*typedef enum hiHDMIRX_PORT_IDX_E
{
    HDMIRX_PORT_0,
    HDMIRX_PORT_1,
    HDMIRX_PORT_2,
    HDMIRX_PORT_3,
    HDMIRX_PORT_ALL,
    HDMIRX_PORT_BUTT
}HDMIRX_PORT_IDX_E;*/

typedef enum hiHDMIRX_AUTO_CFG_IDX
{
    HDMIRX_AUTO_CFG_VDO,
    HDMIRX_AUTO_CFG_AUD,
    HDMIRX_AUTO_CFG_AUD_OUT,
    HDMIRX_AUTO_CFG_ALL,
    HDMIRX_AUTO_CFG_BUTT
}HDMIRX_AUTO_CFG_IDX;

typedef enum hiHDMIRX_MUTE_TYPE
{
    HDMIRX_MUTE_VDO,
    HDMIRX_MUTE_AUD,
    HDMIRX_MUTE_ALL,
    HDMIRX_MUTE_BUTT
}HDMIRX_MUTE_TYPE;

typedef enum hiHDMIRX_RESET_TYPE
{
    HDMIRX_HDCP_RST,
    HDMIRX_DC_FIFO_RST,
    HDMIRX_AUDIO_FIFO_RST,
    HDMIRX_AAC_RST,
    HDMIRX_SOFT_RST,
    HDMIRX_BUS_RST,
    HDMIRX_DDC_RST,
    HDMIRX_ACR_RST,
    HDMIRX_HDMIM_RST,
    HDMIRX_ALL_RST,   
    HDMIRX_RST_BUTT
}HDMIRX_RESET_TYPE;

typedef enum hiHDMIRX_AUTO_RESET_TYPE
{
    HDMIRX_AUTORST_HDCP,
    HDMIRX_AUTORST_AUDIO_FIFO,
    HDMIRX_AUTORST_ACR,
    HDMIRX_AUTORST_SOFT,
    HDMIRX_AUTORST_ALL,
    HDMIRX_AUTORST_BUTT
}HDMIRX_AUTO_RESET_TYPE;

typedef enum hiHDMIRX_MHL_Reg_TYPE
{
    HDMIRX_MHL_CBUS_INT0,
    HDMIRX_MHL_CBUS_INT1,
    HDMIRX_MHL_INT0,
    HDMIRX_MHL_STAT_0,
    HDMIRX_MHL_STAT_1,
    HDMIRX_MHL_Reg_ALL,
    HDMIRX_MHL_Reg_BUTT
}HDMIRX_MHL_Reg_TYPE;

typedef enum hiHDMIRX_ABORT_TYPE
{
    HDMIRX_CEC_ABORT,
    HDMIRX_DDC_ABORT,
    HDMIRX_MSC_MR_ABORT,
    HDMIRX_ABORT_ALL,
    HDMIRX_ABORT_BUTT
}HDMIRX_ABORT_TYPE;
  
typedef enum hiHDMIRX_TERM_CTL
{
    HDMIRX_TERM_CTL_52,
    HDMIRX_TERM_CTL_51,
    HDMIRX_TERM_CTL_49,
    HDMIRX_TERM_CTL_48,
    HDMIRX_TERM_CTL_47,
    HDMIRX_TERM_CTL_46,
    HDMIRX_TERM_CTL_45,
    HDMIRX_TERM_CTL_44,
    HDMIRX_TERM_CTL_BUTT  
}HDMIRX_TERM_CTL;

typedef enum hiHDMIRX_TERM_SEL
{
    HDMIRX_TERM_SEL_HDMI,
    HDMIRX_TERM_SEL_MHL,
    HDMIRX_TERM_SEL_OPEN =3 ,
    HDMIRX_TERM_SEL_BUTT 
}HDMIRX_TERM_SEL;

HI_BOOL HDMIRX_HAL_GetCkdt(HI_UNF_HDMIRX_PORT_E enPort);
HI_U32 HDMIRX_HAL_ReadFldAlign(HI_UNF_HDMIRX_PORT_E enPort,HI_U32 u32Addr, HI_U32 u32Mask);
HI_VOID HDMIRX_HAL_WriteFldAlign(HI_UNF_HDMIRX_PORT_E enPort,HI_U32 u32Addr, HI_U32 u32Mask, HI_U32 u32Value);
HI_VOID HDMIRX_HAL_SetResetEn(HI_UNF_HDMIRX_PORT_E enPort,HDMIRX_RESET_TYPE enRst, HI_BOOL bEn);
HI_VOID HDMIRX_HAL_ClearAvMute(HI_UNF_HDMIRX_PORT_E enPort,HI_BOOL bEn);
HI_VOID HDMIRX_HAL_SetMuteEn(HI_UNF_HDMIRX_PORT_E enPort,HDMIRX_MUTE_TYPE enType, HI_BOOL bEn);
HI_VOID HDMIRX_HAL_ClearInterrupt(HI_UNF_HDMIRX_PORT_E enPort,HDMIRX_INTERRUPT_IDX enIdx);
HI_VOID HDMIRX_HAL_SetAutoRstEn(HI_UNF_HDMIRX_PORT_E enPort,HDMIRX_AUTO_RESET_TYPE enAutoRst, HI_BOOL bEn);
HI_BOOL HDMIRX_HAL_GetScdt(HI_UNF_HDMIRX_PORT_E enPort);
HI_BOOL HDMIRX_HAL_GetHdcpDone(HI_UNF_HDMIRX_PORT_E enIdx);
HI_BOOL HDMIRX_HAL_GetPwr5vStatus(HI_UNF_HDMIRX_PORT_E enIdx);
HI_BOOL HDMIRX_HAL_IsInterrupt(HI_UNF_HDMIRX_PORT_E enPort);
HI_VOID HDMIRX_HAL_GetInterruptSta(HI_UNF_HDMIRX_PORT_E enPort,HI_U32 *pu32Int);
HI_VOID HDMIRX_HAL_SetInterruptSta(HI_UNF_HDMIRX_PORT_E enPort,HI_U32 *pu32Int);
HI_U32 HDMIRX_HAL_GetAviType(HI_UNF_HDMIRX_PORT_E enPort);
HI_VOID HDMIRX_HAL_SelectPort(HI_U32 u32Port);
HI_VOID HDMIRX_HAL_ClearAudioInt(HI_UNF_HDMIRX_PORT_E enPort);
HI_VOID HDMIRX_HAL_SetInterruptEn(HI_UNF_HDMIRX_PORT_E enPort,HDMIRX_INTERRUPT_IDX enIdx, HI_BOOL bEn);
HI_VOID HDMIRX_HAL_SwitchVsifDec(HI_UNF_HDMIRX_PORT_E enPort,HI_BOOL bVsif);
HI_VOID HDMIRX_HAL_SetAviIntOnlyNew(HI_UNF_HDMIRX_PORT_E enPort,HI_BOOL bNew);
HI_VOID HDMIRX_HAL_AudioInfoFrameIntCfg(HI_UNF_HDMIRX_PORT_E enPort,HI_BOOL bAny);
#if SUPPORT_AEC
HI_VOID HDMIRX_HAL_SetResChangeAecEn(HI_UNF_HDMIRX_PORT_E enPort,HI_BOOL bEn);
#endif
HI_BOOL HDMIRX_HAL_GetMuteSta(HI_UNF_HDMIRX_PORT_E enPort);
HI_U32 HDMIRX_HAL_GetPacketType(HI_UNF_HDMIRX_PORT_E enPort,HI_U32 u32Addr);
HI_VOID HDMIRX_HAL_Setvidpath(HI_UNF_HDMIRX_PORT_E enPort,HI_U32 bEn);
HI_U32 HDMIRX_HAL_Getvidpath(HI_UNF_HDMIRX_PORT_E enPort);
HI_VOID HDMIRX_HAL_SetCoreiso(HI_UNF_HDMIRX_PORT_E enPort,HI_U32 bEn);
HI_U32 HDMIRX_HAL_GetCoreiso(HI_UNF_HDMIRX_PORT_E enPort);
HI_VOID HDMIRX_HAL_GetPacketContent(HI_UNF_HDMIRX_PORT_E enPort,HI_U32 u32Addr, 
    HI_U32 *au32Data, HI_U32 u32Length);
HI_U32 HDMIRX_HAL_GetReplication(HI_UNF_HDMIRX_PORT_E enPort);
HI_U32 HDMIRX_HAL_GetHtotal(HI_UNF_HDMIRX_PORT_E enPort);
HI_U32 HDMIRX_HAL_GetVtotal(HI_UNF_HDMIRX_PORT_E enPort);
HI_U32 HDMIRX_HAL_GetPixClk(HI_UNF_HDMIRX_PORT_E enPort);
HI_BOOL HDMIRX_HAL_GetInterlance(HI_UNF_HDMIRX_PORT_E enPort);
HI_BOOL HDMIRX_HAL_GetHpol(HI_UNF_HDMIRX_PORT_E enPort);
HI_BOOL HDMIRX_HAL_GetVpol(HI_UNF_HDMIRX_PORT_E enPort);
HDMIRX_INPUT_WIDTH_E HDMIRX_HAL_GetDeepColorSta(HI_UNF_HDMIRX_PORT_E enPort);
HI_VOID HDMIRX_HAL_SetDeepColor(HI_UNF_HDMIRX_PORT_E enPort, HDMIRX_INPUT_WIDTH_E enMode);
HI_VOID HDMIRX_HAL_SetBlankLv(HI_UNF_HDMIRX_PORT_E enPort,HI_U32 *pau32BlankLv);
HI_U32 HDMIRX_HAL_GetOclkCfg(HI_UNF_HDMIRX_PORT_E enPort);
HI_VOID HDMIRX_HAL_SetOclkCfg(HI_UNF_HDMIRX_PORT_E enPort,HI_U32 u32Cfg);
HI_U32 HDMIRX_HAL_GetDitherMode(HI_UNF_HDMIRX_PORT_E enPort);
HI_VOID HDMIRX_HAL_SetOutFormat(HI_UNF_HDMIRX_PORT_E enPort,HI_U32 *pau32Format);
HI_VOID HDMIRX_HAL_SetChannelMap(HI_UNF_HDMIRX_PORT_E enPort,HDMIRX_COLOR_SPACE_E enColor, HDMIRX_OVERSAMPLE_E enReplication);
HI_VOID HDMIRX_HAL_ClearT4Error(HI_UNF_HDMIRX_PORT_E enPort);
HI_U32 HDMIRX_HAL_GetAudp(HI_UNF_HDMIRX_PORT_E enPort);
HI_U32 HDMIRX_HAL_GetCts(HI_UNF_HDMIRX_PORT_E enPort);
HI_BOOL HDMIRX_HAL_IsAudioPacketGot(HI_UNF_HDMIRX_PORT_E enPort);
HI_BOOL HDMIRX_HAL_IsCtsGot(HI_UNF_HDMIRX_PORT_E enPort);
HI_BOOL HDMIRX_HAL_IsClockStable(HI_UNF_HDMIRX_PORT_E enPort);
HI_BOOL HDMIRX_HAL_IsFifoStable(HI_UNF_HDMIRX_PORT_E enPort);
HI_VOID HDMIRX_HAL_GetChannelSta(HI_UNF_HDMIRX_PORT_E enPort,HI_U32 *pau32Data);
HI_U32 HDMIRX_HAL_GetHwSampleRate(HI_UNF_HDMIRX_PORT_E enPort);
HI_VOID HDMIRX_HAL_SetExceptionEn(HI_UNF_HDMIRX_PORT_E enPort,HI_BOOL bEn);
HI_VOID HDMIRX_HAL_SetSpdifOutEn(HI_UNF_HDMIRX_PORT_E enPort,HI_BOOL bOut);
HI_U32 HDMIRX_HAL_GetN(HI_UNF_HDMIRX_PORT_E enPort);
HI_VOID HDMIRX_HAL_SetMclk(HI_UNF_HDMIRX_PORT_E enPort,HI_U32 u32Code);
HI_VOID HDMIRX_HAL_SetFsSel(HI_UNF_HDMIRX_PORT_E enPort,HI_BOOL bSoft);
HI_VOID HDMIRX_HAL_SetI2sOutCfg(HI_UNF_HDMIRX_PORT_E enPort,HI_U32 u32Cfg);
HI_VOID HDMIRX_HAL_SetI2sOutDft(HI_UNF_HDMIRX_PORT_E enPort);
HI_VOID HDMIRX_HAL_SetHwMute(HI_UNF_HDMIRX_PORT_E enPort,HI_BOOL bHw);
HI_VOID HDMIRX_HAL_AudioRegInit(HI_UNF_HDMIRX_PORT_E enPort);
HI_VOID HDMIRX_HAL_DisableI2sOut(HI_UNF_HDMIRX_PORT_E enPort);
HI_U32 HDMIRX_HAL_GetLayout(HI_UNF_HDMIRX_PORT_E enPort);
HI_VOID HDMIRX_HAL_SetAcrStart(HI_UNF_HDMIRX_PORT_E enPort);
HI_U32 HDMIRX_HAL_GetDeviceId(HI_UNF_HDMIRX_PORT_E enPort);
HI_U32 HDMIRX_HAL_GetDeviceReversion(HI_UNF_HDMIRX_PORT_E enPort);
HI_VOID HDMIRX_HAL_InterruptRegInit(HI_UNF_HDMIRX_PORT_E enPort,HI_U32* pau32IntmaskTable);
HI_VOID HDMIRX_HAL_VideoRegInit(HI_UNF_HDMIRX_PORT_E enPort);
HI_VOID HDMIRX_HAL_PacketRegInit(HI_UNF_HDMIRX_PORT_E enPort);
HI_BOOL HDMIRX_HAL_GetHdmiMode(HI_UNF_HDMIRX_PORT_E enPort);
HI_VOID HDMIRX_HAL_SetEdidDdcEn(HI_UNF_HDMIRX_PORT_E ePortIdx, HI_BOOL bEn);
HI_VOID HDMIRX_HAL_SetHdcpDdcEn(HI_UNF_HDMIRX_PORT_E ePortIdx, HI_BOOL bEn);
HI_VOID HDMIRX_HAL_SetHpdLevel(HI_UNF_HDMIRX_PORT_E enPort, HI_BOOL bHigh);
HI_VOID HDMIRX_HAL_EdidInit(HI_U32* pau32EdidTable,HI_U32* pau32Addr);
HI_VOID HDMIRX_HAL_LoadHdcpKey(HI_UNF_HDMIRX_PORT_E enPort,HI_BOOL bEn);
HI_VOID HDMIRX_HAL_HdcpCrcCheck(HI_UNF_HDMIRX_PORT_E enPort,HI_U32 u32Port);
HI_S32 HDMIRX_HAL_Init(HI_VOID);
HI_U32 HDMIRX_HAL_GetVactive(HI_UNF_HDMIRX_PORT_E enPort);
HI_VOID HDMIRX_HAL_SetPdSysEn(HI_UNF_HDMIRX_PORT_E enPort, HI_BOOL bEn);
HI_VOID HDMIRX_HAL_SetExtEqEn(HI_UNF_HDMIRX_PORT_E enPort,HI_BOOL bMain,HI_BOOL bEn);
HI_U32 HDMIRX_HAL_GetHactive(HI_UNF_HDMIRX_PORT_E enPort);
HI_VOID HDMIRX_HAL_SetHpdManual(HI_UNF_HDMIRX_PORT_E enPort, HI_BOOL bEn);
HI_VOID HDMIRX_HAL_MHLInit(HI_UNF_HDMIRX_PORT_E enPort);
HI_VOID HDMIRX_HAL_SetMhlEn(HI_BOOL bEn);
HI_VOID HDMIRX_HAL_SetGPIO5_1(HI_BOOL bEn);
HI_BOOL HDMIRX_HAL_GetCbusSense(HI_UNF_HDMIRX_PORT_E enPort);
HI_VOID HDMIRX_HAL_MHLSetCbus1x(HI_UNF_HDMIRX_PORT_E enPort,HI_BOOL bEn);
HI_VOID HDMIRX_HAL_MHLSetCmd_Offset(HI_UNF_HDMIRX_PORT_E enPort,HI_U32 Cmd_Offset);
HI_VOID HDMIRX_HAL_MHLSet1STDATA(HI_UNF_HDMIRX_PORT_E enPort,HI_U32 Data);
HI_VOID HDMIRX_HAL_MHLSet2NDDATA(HI_UNF_HDMIRX_PORT_E enPort,HI_U32 Data);
HI_VOID HDMIRX_HAL_MHLSetBustLen(HI_UNF_HDMIRX_PORT_E enPort,HI_U32 Len);
HI_VOID HDMIRX_HAL_MHLSetCmdStart(HI_UNF_HDMIRX_PORT_E enPort,HI_U32 u32Startbit);
HI_U32 HDMIRX_HAL_MHLReadReg(HI_UNF_HDMIRX_PORT_E enPort,HDMIRX_MHL_Reg_TYPE Reg_Type);
HI_VOID HDMIRX_HAL_MHLWriteReg(HI_UNF_HDMIRX_PORT_E enPort,HDMIRX_MHL_Reg_TYPE Reg_Type,HI_U32 U32Ret);
HI_U32 HDMIRX_HAL_MSC_RCVD_1STDATA(HI_UNF_HDMIRX_PORT_E enPort);
HI_U32 HDMIRX_HAL_MSC_RCVD_2NDDATA(HI_UNF_HDMIRX_PORT_E enPort);
HI_U32 HDMIRX_HAL_MSCMT_RCVD_DATA0(HI_UNF_HDMIRX_PORT_E enPort);
HI_U32 HDMIRX_HAL_MSCMT_RCVD_DATA1(HI_UNF_HDMIRX_PORT_E enPort);
HI_BOOL HDMIRX_HAL_GetCBUS_Connected(HI_UNF_HDMIRX_PORT_E enPort);
HI_U32 HDMIRX_HAL_GetABORT_INT(HI_UNF_HDMIRX_PORT_E enPort,HDMIRX_ABORT_TYPE ABORT_TYPE);
HI_VOID HDMIRX_HAL_SetABORT_INT(HI_UNF_HDMIRX_PORT_E enPort,HDMIRX_ABORT_TYPE ABORT_TYPE,HI_U32 U32Ret);
HI_VOID HDMIRX_HAL_SetTermValue(HI_UNF_HDMIRX_PORT_E enPort, HDMIRX_TERM_CTL enValue);
HI_VOID HDMIRX_HAL_SetTermMode(HI_UNF_HDMIRX_PORT_E enPort, HDMIRX_TERM_SEL enMode);
HI_VOID HDMIRX_HAL_SetHpdPullUpEn(HI_UNF_HDMIRX_PORT_E enPort, HI_BOOL bEn);
HI_VOID HDMIRX_HAL_MHLDevcapInit(HI_UNF_HDMIRX_PORT_E enPort,HI_U32 u32Addr , HI_U32 u32Value);
HI_VOID HDMIRX_HAL_MHL_SENSE_Enable(HI_BOOL bEn);
#if SUPPORT_DOUBLE_CTRL
HI_VOID HDMIRX_HAL_SetAudioMux(HI_UNF_HDMIRX_PORT_E enPort);
#endif
//HI_U32 HDMIRX_HAL_Readtmp(HI_VOID);
HI_U32 HDMIRX_HAL_GetBchErrCnt(HI_UNF_HDMIRX_PORT_E enPort); 
HI_U32 HDMIRX_HAL_GetHdcpErrCnt(HI_UNF_HDMIRX_PORT_E enPort);
HI_VOID HDMIRX_HAL_WriteBlock(HI_UNF_HDMIRX_PORT_E enPort,HI_U32 u32Addr, HI_U32 *pSrc, HI_U32 u32Num);
HI_VOID HDMIRX_HAL_ReadBlock(HI_UNF_HDMIRX_PORT_E enPort,HI_U32 u32Addr, HI_U32 *pDst, HI_U32 u32Num);
HI_U32 HDMIRX_HAL_GetEQtable(HI_UNF_HDMIRX_PORT_E enPort,HI_U32 u32cnt);
HI_VOID HDMIRX_HAL_SetEQtable(HI_UNF_HDMIRX_PORT_E enPort,HI_U32 u32cnt,HI_U32 u32Value);
HI_VOID HDMIRX_HAL_SetHpdValue(HI_UNF_HDMIRX_PORT_E enPort, HI_BOOL bValue);
HI_VOID HDMIRX_HAL_HpdOenEn(HI_UNF_HDMIRX_PORT_E enPort, HI_BOOL bValue);
HI_VOID HDMIRX_HAL_MHLRstEn(HI_BOOL bEn);
HI_VOID HDMIRX_HAL_MhlChRstEn(HI_BOOL bEn);

#endif

